FROM ubuntu

RUN apt-get update && apt-get install -y \
	iproute2 \
	tcpdump \
	iputils-ping \
	net-tools \
	bind9-utils \
	dnsutils \
	vim \
	inetutils-traceroute \
	procps \
	iptables \
	nano \
	curl \
	unbound

RUN chown root:unbound /etc/unbound

RUN mkdir -p /etc/unbound

COPY ./final/resolvers /init
COPY final/resolvers/unbound.conf /etc/unbound/unbound.conf
COPY final/resolvers/root.hints /etc/unbound/root.hints
COPY final/resolvers/resolver-start-up.sh /resolver-start-up.sh
COPY ./init/vimrc /vimrc

EXPOSE 53/tcp
EXPOSE 53/udp

CMD ["/resolver-start-up.sh"]