FROM ubuntu

RUN apt-get update && apt-get install -y iproute2 \
    tcpdump \
    iputils-ping \
    net-tools \
    bind9-utils \
    dnsutils \
    vim \
    inetutils-traceroute \
    mtr \
    iptables \
    nano \
    busybox \
    curl \
    links 

RUN apt-get install -y procps

COPY ./init/routers /init
COPY ./init/routers/router-start-up.sh /router-start-up.sh
COPY ./init/vimrc /vimrc

CMD ["/router-start-up.sh"]
