FROM ubuntu

RUN apt-get update && apt-get install -y iproute2 \
    tcpdump \
    iputils-ping \
    net-tools \
    bind9-utils \
    dnsutils \
    vim \
    inetutils-traceroute \
    mtr \
    iptables \
    nano \
    busybox \
    curl \
    links 

RUN apt-get install -y procps

COPY ./{{ config_dir }}/hosts /init
# COPY www /home/www
COPY ./{{ config_dir }}/hosts/host-start-up.sh /host-start-up.sh
COPY ./init/vimrc /vimrc

CMD ["/host-start-up.sh"]
