let mapleader=","
set backspace=indent,eol,start
set cursorline
set encoding=utf-8
set expandtab
set history=1000
set hlsearch
set incsearch
set ignorecase
set laststatus=2
set list listchars=tab:»·,trail:·,nbsp:·
set nocompatible
set nowrap
set number
set numberwidth=5
set ruler
set showcmd
set showtabline=2
set shiftround
set shiftwidth=2
set smartcase
set softtabstop=2
set statusline=%F\ %r\ %y\ format:\ %{&ff};\ [%c,%l]
set tabstop=2
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*
set splitbelow
set splitright
set textwidth=80
set winwidth=90
set winheight=20
nnoremap <CR> :nohlsearch<cr>
map Y y$
map D d$
map <leader>s :w<cr>
imap <leader>s <esc>:w<cr>
