# If we run BIRD interactively, we can see logs go by for everything
# it's doing
debug protocols all;

protocol device {
  scan time 10;
}

protocol direct {
  interface "*";
}

# One filter to rule them all
filter no_192_168_0 {
  if net = 192.168.0.0/24 then reject;
  accept;
}

protocol kernel {
  import none;

  # Recommended: don't leak the NAT net into Linux from BIRD either
  export filter no_192_168_0;
}

protocol ospf {
  # Don't advertise it
  export filter no_192_168_0;

  # Don't learn it
  import filter no_192_168_0;

  area 0 {
    interface "*" {
      type broadcast;
      hello 10;
      wait 40;
      dead 40;
    };
  };
}