FROM ubuntu

RUN apt-get update && apt-get install -y iproute2 \
    tcpdump \
    iputils-ping \
    net-tools \
    bind9-utils \
    dnsutils \
    vim \
    inetutils-traceroute \
    mtr \
    iptables \
    nano \
    busybox \
    curl \
    links \
    procps \
    bird-bgp

COPY ./{{ config_dir }}/router-start-up.sh /router-start-up.sh
{% if config_dir == "final" %}
COPY ./final/bird.conf /bird.conf
{% endif %}

RUN mkdir -p /etc/vim
COPY .vimrc /etc/vim/vimrc.local

CMD ["/router-start-up.sh"]
