FROM ghcr.io/letsencrypt/pebble:latest

RUN apt-get update && apt-get install -y iproute2 \
    procps \
    tcpdump \
    iputils-ping \
    net-tools \
    bind9-utils \
    dnsutils \
    vim \
    inetutils-traceroute \
    iptables \
    nano \
    curl

# COPY ./init/dns-servers /init

# COPY ./init/tls/tls-start-up.sh /tls-start-up.sh
COPY ./init/vimrc /vimrc

CMD ["/tls-start-up.sh"]
