FROM ubuntu

RUN apt-get update && apt-get install -y iproute2 \
    tcpdump \
    iputils-ping \
    net-tools \
    bind9-utils \
    dnsutils \
    vim \
    inetutils-traceroute \
    mtr \
    iptables \
    nano \
    busybox \
    curl \
    links \
    procps \
    bird-bgp

COPY ./init/router-start-up.sh /router-start-up.sh
# Uncommend these lines and comment the line above if you want to run the "final" configuration
# COPY ./final/bird.conf /bird.conf
# COPY ./final/router-start-up.sh /router-start-up.sh
RUN mkdir -p /etc/vim
COPY ./init/vimrc /etc/vim/vimrc.local

CMD ["/router-start-up.sh"]
