FROM ubuntu

RUN apt-get update && apt-get install -y \
	iproute2 \
	tcpdump \
	iputils-ping \
	net-tools \
	bind9-utils \
	dnsutils \
	vim \
	inetutils-traceroute \
	procps \
	iptables \
	nano \
	curl \
	unbound

RUN chown root:unbound /etc/unbound

RUN mkdir -p /etc/unbound

COPY ./{{ config_dir }}/resolvers /init
COPY {{ config_dir }}/resolvers/unbound.conf /etc/unbound/unbound.conf
COPY {{ config_dir }}/resolvers/root.hints /etc/unbound/root.hints
COPY {{ config_dir }}/resolvers/resolver-start-up.sh /resolver-start-up.sh
RUN mkdir -p /etc/vim
COPY .vimrc /etc/vim/vimrc.local

EXPOSE 53/tcp
EXPOSE 53/udp

CMD ["/resolver-start-up.sh"]
