FROM cznic/knot

RUN apt-get update && apt-get install -y iproute2 \
    tcpdump \
    iputils-ping \
    net-tools \
    bind9-utils \
    dnsutils \
    vim \
    inetutils-traceroute \
    mtr \
    iptables \
    nano \
    busybox \
    curl \
    links

COPY /init/ /init
COPY ./init/dns-start-up.sh /dns-start-up.sh


CMD ["/dns-start-up.sh"]
