FROM ubuntu

RUN apt-get update && apt-get install -y iproute2 \
    tcpdump \
    iputils-ping \
    net-tools \
    bind9-utils \
    dnsutils \
    vim \
    inetutils-traceroute \
    mtr \
    iptables \
    nano \
    busybox \
    curl \
    links \
    procps \
    bird-bgp

COPY ./init/router-start-up.sh /router-start-up.sh
COPY ./init/set-router-addys.sh /set-router-addys.sh
COPY ./init/bird.conf /bird.conf

RUN mkdir -p /etc/vim
COPY .vimrc /etc/vim/vimrc.local

CMD ["/router-start-up.sh"]
